### ISSUE TITLE
Restrict Question List

### ISSUE THREAD

**Issue by GeorginaFraire** [wizeline/wize-q-remix#105]
Restrict the question list in the home page to show just the ones in the last 3 months.

**Comment by albertcastaned** [comment]
@GeorginaFraire Should we also redirect to 404 when we access the question detail through a link or let it be accesible?

**Comment by GeorginaFraire** [comment]
We let it be accessible by the link.

**Comment by GeorginaFraire** [comment]
The purpose of this is to make them respond faster, since they won't be visible all the time.

**Comment by albertcastaned** [comment]
> The purpose of this is to make them respond faster, since they won't be visible all the time.

Sounds good! 👍

**Comment by albertcastaned** [comment]
For simplicity, is it okay to filter starting officialy from September 1th 2022? @GeorginaFraire
