### ISSUE TITLE
BUG: Interaction count back navigation. 

### ISSUE THREAD

**Issue by GeorginaFraire** [wizeline/wize-q-remix#118]
When a user goes to the detail of the question, and interacts by voting the questions or comments, depending on the number of interactions, is going to be the clicks on the back navigation of the browser to return to the homepage. 

https://user-images.githubusercontent.com/97203617/205138621-2ad41b15-74b8-4bc4-8f77-d058b5dd8487.mov

**Comment by albertcastaned** [comment]
@GeorginaFraire  My guess (need to test locally) is that changing the `replace: false` to `true` in here https://github.com/wizeline/wize-q-remix/blob/master/app/components/ListQuestions/ListQuestions.jsx#L95 will solve the bug.
