### ISSUE TITLE
Add message from POP's.

### ISSUE THREAD

**Issue by GeorginaFraire** [wizeline/wize-q-remix#128]
Add the following message in the homepage. 

> Hello, {{firstname}}!
> Welcome to Wize Q! We want to share a few simple guidelines before you start.
> Remember that Wize Q is a space for asking questions and providing answers that are helpful to our community.
> Please practice our values when using Wize Q:
>  - **Ownership** – See if you can find the answer to your question before posting on Wize Q. And if you know the answer to a question or how to find it, be sure to reply — anyone can!
>  - **Innovation** – When someone shares a concern or challenge, let’s be innovative — propose a solution or offer support!
> - **Community** – Remember to treat everyone with dignity and respect. Assume others have good intentions. Always be honest and constructive. Let’s make Wizeline a community where everyone can thrive.
> 
>Consider that other channels (ticketing portal, Slack, or your manager or people partner) might be more effective for finding the right answer quickly.
> Thanks for being a valuable contributor to our community!
> The Wize Q Team

**Comment by GeorginaFraire** [comment]
Proposal.

<img width="1206" alt="Screen Shot 2022-12-14 at 12 24 56" src="https://user-images.githubusercontent.com/97203617/207677608-a18c4871-bddf-40d9-8a61-7242b8ace153.png">

**Comment by GeorginaFraire** [comment]
Proposal 2
<img width="1188" alt="Screen Shot 2022-12-14 at 12 39 09" src="https://user-images.githubusercontent.com/97203617/207683125-c82c88a5-4293-47ff-9de2-106d78d5a526.png">

**Comment by albertcastaned** [comment]
I vote with Proposal 1, using a cookie to only show it on first login / cache clear 😄
