### ISSUE TITLE
New Page to show anonymous questions.

### ISSUE THREAD

**Issue by GeorginaFraire** [wizeline/wize-q-remix#141]
Create a new page to show the anonymous questions with less than 10 votes (positive) 
Is going to be like the home page

- Add new field `is_public`
- Create new query similar to the question list and add new condition to show the anonymous questions and privates one (`is_public = false`)

_Note: the private questions are the ones that are anonymous and have less than 10 votes (positive), the public questions are the ones that have more than 10 votes if they are anonymous and the ones with the user information,_

**Comment by albertcastaned** [comment]
Duplicate of #161
