### ISSUE TITLE
[ADMINS] Dashboard. 

### ISSUE THREAD

**Issue by GeorginaFraire** [wizeline/wize-q-remix#174]
Create a dashboard for admins and show the statistics of:
- Questions made in general per month 
- Time of answering a question per month. 

- can be UI / QUERIES.

**Comment by GeorginaFraire** [comment]
Maybe this one is not going to be finish for this release, because we don't have the enough to create the queries in GCP.
We already asked for them, so we are waiting. 

If this gets too hard, we are going to create the queries in Prisma and create a UI.

**Comment by GeorginaFraire** [comment]
Create the connection following the documentation. https://cloud.google.com/bigquery/docs/connect-to-sql#access-sql
Create two queries. 

One to see all the question created in the last 6 months and, the other to see a summary of the mon

<img width="489" alt="Screen Shot 2023-02-17 at 13 13 29" src="https://user-images.githubusercontent.com/97203617/219765863-e3280795-82d2-42f0-9fe7-398b2bf129c9.png">
<img width="373" alt="Screen Shot 2023-02-18 at 11 43 19" src="https://user-images.githubusercontent.com/97203617/219880459-c917b7f9-caa1-4e63-8cd9-32c3fc0af9fb.png">


<img width="261" alt="Screen Shot 2023-02-17 at 13 09 08" src="https://user-images.githubusercontent.com/97203617/219764945-515444c5-7173-4be3-b861-0e85303326b6.png">

**Comment by GeorginaFraire** [comment]
@albertcastaned  You can check the queries in GCP and if you have another suggestion, please let me know.
Thanks.

**Comment by albertcastaned** [comment]
Looks good to me 👍 does this target develop or production database? @GeorginaFraire

**Comment by GeorginaFraire** [comment]
The results are from production,  but in the queries you can see the connection to dev too. 
https://console.cloud.google.com/bigquery?sq=603531922505:a95587015732407caaec024b852ce447
https://console.cloud.google.com/bigquery?sq=603531922505:b9cb828dcdf84aad85249c3c9cfa1e31
