### ISSUE TITLE
Restrict soft-deleted questions to be displayed to non-admin users

### ISSUE THREAD

**Issue by Carlos-Reyna** [wizeline/wize-q-remix#175]
With the current logic, questions that have the value of "true" at the is_disabled field will be still available throughout the URL. The intention of this issue is to instead of displaying the disabled question (soft-deleted) is to display a message, that displays that the question didn't comply with Wizeline values.

**Comment by albertcastaned** [comment]
Could you add more context to this issue?

**Comment by Carlos-Reyna** [comment]
@albertcastaned , sorry I forgot to update the issue. Do you think more context is needed?

**Comment by albertcastaned** [comment]
It's okay I think it is clear now, thanks ! @Carlos-Reyna

**Comment by GeorginaFraire** [comment]
@Carlos-Reyna @albertcastaned Do you think that showing the 400 page is enough, or do I have to add a message?
<img width="1791" alt="Screen Shot 2023-02-13 at 11 27 58" src="https://user-images.githubusercontent.com/97203617/218529121-1964425e-4d03-4682-b010-9fe6addf3d71.png">
