### ISSUE TITLE
The column `createdAt` contained an invalid datetime value with either day or month set to zero.

### ISSUE THREAD

**Issue by albertcastaned** [wizeline/wize-q-remix#183]
Found in production, questions.wizeline.com. Not reproducible in development environment.

When searching for some questions in the search bar, for example "monterrey", we get the following error.

![image](https://user-images.githubusercontent.com/38927620/217355148-a9432901-75a2-4d2b-b740-77e773978c17.png)

It is possible that some questiosn were created without the 'createdAt' field, or have null values. This ticket is to make the list controller filter out these questions, or handle this error.

**Comment by albertcastaned** [comment]
Attempted to replicate local database with the production one, with the questions that have instance of "monterrey" having the same createdAt fields. However, the error is not happening locally or in develop. Maybe it was fixed by #50 ? Which happened after last release. I will keep this open so we keep an eye out on next release to see if it's fixed.

**Comment by GeorginaFraire** [comment]
This issue was solved.
