### ISSUE TITLE
Create Question: Do not show the option to select a person when there are no options.

### ISSUE THREAD

**Issue by GeorginaFraire** [wizeline/wize-q-remix#194]
<img width="816" alt="Screen Shot 2023-02-28 at 10 41 14" src="https://user-images.githubusercontent.com/97203617/221919258-317122d5-92f6-45f4-ad13-0c0b81238b46.png">

<img width="807" alt="Screen Shot 2023-02-28 at 10 41 31" src="https://user-images.githubusercontent.com/97203617/221919308-a11e73ca-2f92-47fe-8002-7401da4bc4c1.png">

**Comment by StevyCoding** [comment]
hello I am interested in solving this problem.
