### ISSUE TITLE
Choose a source of truth storage for embedding vectors for wize-q data

### ISSUE THREAD

**Issue by jackbravo** [wizeline/wize-q-remix#240]
One of the recommended ways of adding recommendation/search engines that interact with LLMs is to use [embeddings](https://platform.openai.com/docs/guides/embeddings/what-are-embeddings) to transform text strings into vectors that can be later queried for similarity/recommendation searches.

We would like to store vector embeddings of our answers in a long term storage. Some options are:

- Storing them in our MySQL database, which is already the source of truth of our system, as [JSON arrays](https://stackoverflow.com/questions/24346424/how-do-i-create-a-field-with-a-vector-type-in-mysql). MySQL doesn't support vectors, or vector search, so this would be used only to persist the vectors, but searches would be done elsewhere. This is probably the fastest to implement.
- Use a separate vector storage like [sqlite](https://github.com/asg017/sqlite-vss), [weaviate](https://github.com/weaviate/weaviate), [opensearch/elasticsearch](https://opensearch.org/docs/latest/search-plugins/knn/index/) or [faiss](https://github.com/ewfian/faiss-node).
- We've discussed the possibility of switching from MySQL to PostgreSQL. So maybe this would be a good reason to make the swtich. Since Postgres does support vector columns and search opperations in them.

**Comment by albertcastaned** [comment]
Migrated completely to Postgres
