### ISSUE TITLE
Update development local setup documentation for Postgres

### ISSUE THREAD

**Issue by albertcastaned** [wizeline/wize-q-remix#262]
As of 521fd8c2c7e5e78047e71a90dc599162fcd7e210,  we've now migrated to Postgres as a DB engine. This ticket is to update the onboarding documentation to reflect the changes, so that newcomers use the current stack.

**Comment by GeorginaFraire** [comment]
Documentation updated ✅ 
also the .env in keybase
https://github.com/wizeline/wize-q-remix/wiki/How-to-setup-local-environment

**Comment by albertcastaned** [comment]
Thank you!
