### ISSUE TITLE
Hidden disrespectful comments

### ISSUE THREAD

**Issue by Hoosep** [wizeline/wize-q-remix#265]
Wizeline Questions turned into disrespectul comments. Ideally it would be great to find a way to hide those disrespectul comments.

Suggestions:

![Image](https://user-images.githubusercontent.com/31190865/264177007-11a162b9-4efd-44fd-9b6f-807df8e162d7.png)
![Image](https://user-images.githubusercontent.com/31190865/264177008-1f5d3ed7-2d06-457e-9d7a-9b154f42822e.png)
![Image](https://user-images.githubusercontent.com/31190865/264177009-1c7206dd-9c03-4f9f-9c8f-0c61e0a1ae3d.png)

**Comment by albertcastaned** [comment]
I've split this into multiple issues. Will be closing this in favor of those if that's okay 😄
