### ISSUE TITLE
Change style and hide comments that are tagged

### ISSUE THREAD

**Issue by albertcastaned** [wizeline/wize-q-remix#266]
Originally https://github.com/wizeline/wize-q-remix/issues/265

This issue is to display the tag's message mapped value in the comment, and make the user have to click on it in order to display it. One idea can be blurring or displaying blank until it is clicked on to display the comment's text.  Note that the exact text for each type of tag is still not defined, please consult with a stakeholder to see some options.

This is purely from the frontend side, assuming the comment's data has the tag values (if not, please mock this for testing and we can enable the feature flag once it's ready). The option for the admin to "tag" a comment from frontend will be handled in another ticket.

Note that it is important that the message displays why is it hidden/shows the tag's message and that the user can see it once clicked.

Please make this configurable [via a feature flag](https://github.com/wizeline/wize-q-remix/blob/master/app/config/flags.json), so that we can enable and disable easily.

Some concept images
![image](https://github.com/wizeline/wize-q-remix/assets/38927620/1389a53c-4e68-4a61-98ea-7ad30becaef3)

![image](https://github.com/wizeline/wize-q-remix/assets/38927620/5594ddcb-9194-4e8d-a092-8b10bcb9ed06)

**Comment by Hoosep** [comment]
Team, if you don't mind, I would like to take this issue.

Please, let me know if I can take it to do it and how it's the process you have before do it! Thnkss!

**Comment by albertcastaned** [comment]
Hello @Hoosep , go ahead! You will probably need to go through the[ local setup ](https://github.com/wizeline/wize-q-remix/wiki/How-to-setup-local-environment). Please ask me or @GeorginaFraire if you have any questions
