### ISSUE TITLE
Create data schema for comment tags

### ISSUE THREAD

**Issue by albertcastaned** [wizeline/wize-q-remix#267]
Originally https://github.com/wizeline/wize-q-remix/issues/265

This issue is to create via Prisma the data schema that will be used to "tag" comments. The data that should be stored is "tag type" which should be numeric. This would later be mapped in the frontend with easy-to-change messages. Example:

tag_type, message
1, hidden by admin because violates X
2, hidden by admin because violates Y

In the future, we are looking to make this tagging be possible to be predicted with ML. To differentiate human and predicted tagging, we should add another field called "taggedBy" as a string. Humans would be saved as the admin name and for ML we could have different strings depending on the model/version used.

One idea of structure could be.

Add a nullable column named `tagCategory` to `Comments` table. This would be numeric and would represent the kind of tag added. Another field would be "taggedBy" with the name of the admin, or in the future could be the name of the model.

Pending to confirm if for human tags we should save who tagged it, or should it remain anonymous.

**Comment by Hoosep** [comment]
Love it!

Just I was thinking that we can change the message in the tag, something like "Hidden comment because violates community policies".

I wouldn't like to add "by admin" since I don't wanna create a kind of bias between admins and original posters (Wizeliners).

**Comment by Hoosep** [comment]
I am okay with save who tagged it that comment just for internal purposes but no for showing up to regular users.

**Comment by albertcastaned** [comment]
@Hoosep Agreed, personally would think saving the username of who tagged it but not displaying it would be best. Regarding the message comment, what I tried to say is we can have a list of "tag categories", each with a different message that would be displayed. We could make the default one "Hidden comment because violates community policies", but open the possibilites for other kind of tags. Not sure if that makes sense 😅
