### ISSUE TITLE
Add vote question functionality

### ISSUE THREAD

**Issue by AldoDominguezWizeline** [wizeline/wize-q-remix#35]
Add the vote question functionality in the list of questions

**Comment by albertcastaned** [comment]
@AldoDominguezWizeline There IS a ticket you were right haha, it was in the blocked column though hahaha. We could close that one or each to avoid repetition #22

**Comment by AldoDominguezWizeline** [comment]
@albertcastaned Got that! I'll be mindful to close both once the task is done, thank you very much!
