### ISSUE TITLE
Add redirect from old question links

### ISSUE THREAD

**Issue by albertcastaned** [wizeline/wize-q-remix#72]
Legacy app used links with the format `https://questions.wizeline.com/#/?questionId=1440` . With Remix, we now use the format `https://questions.wizeline.com/<questionId>/  `to get the detail of a question. This ticket is to add a redirect rule when you add ?questionId prop to the route. This could be achieved through the homepage's `loader`. This will allow support for old links in the Slack channels to work with the new app.

**Comment by GeorginaFraire** [comment]
I cannot add this in the loader, because the hash is not sent to the server, but I put the logic in the useEffect hook.
https://github.com/remix-run/remix/issues/1574
